/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VV9LmLoSBI2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function temp() {
  return (
    (<div
      className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div
        className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 w-full max-w-md">
        <div className="mb-4">
          <input
            className="w-full px-4 py-2 rounded-lg bg-gray-100 dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            readOnly
            type="text" />
        </div>
        <div className="grid grid-cols-4 gap-4">
          <Button
            className="text-gray-500 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            AC
          </Button>
          <Button
            className="text-gray-500 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            +/-
          </Button>
          <Button
            className="text-gray-500 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            %
          </Button>
          <Button
            className="text-orange-500 dark:text-orange-400 hover:bg-orange-100 dark:hover:bg-orange-700 font-bold"
            variant="outline">
            ÷
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            7
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            8
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            9
          </Button>
          <Button
            className="text-orange-500 dark:text-orange-400 hover:bg-orange-100 dark:hover:bg-orange-700 font-bold"
            variant="outline">
            x
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            4
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            5
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            6
          </Button>
          <Button
            className="text-orange-500 dark:text-orange-400 hover:bg-orange-100 dark:hover:bg-orange-700 font-bold"
            variant="outline">
            -
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            1
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            2
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            3
          </Button>
          <Button
            className="text-orange-500 dark:text-orange-400 hover:bg-orange-100 dark:hover:bg-orange-700 font-bold"
            variant="outline">
            +
          </Button>
          <Button
            className="col-span-2 text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            0
          </Button>
          <Button
            className="text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700"
            variant="outline">
            .
          </Button>
          <Button
            className="text-white bg-orange-500 dark:bg-orange-400 hover:bg-orange-600 dark:hover:bg-orange-500 font-bold"
            variant="outline">
            =
          </Button>
        </div>
      </div>
    </div>)
  );
}
